### ISSUE TITLE
android.view.InflateException

### ISSUE THREAD

**Issue by fermedina** [bowyer-app/FabTransitionLayout#21]
Hi.

I have tried use your library in my Android project with Kotlin. When I run my app I get the following error:

java.lang.RuntimeException: Unable to start activity ComponentInfo{twogetherbank.com.lottie/twogetherbank.com.lottie.MainActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.bowyer.app.fabtransitionlayout.BottomSheetLayout
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:154)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:234)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                           Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.bowyer.app.fabtransitionlayout.BottomSheetLayout
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                              at twogetherbank.com.lottie.MainActivity.onCreate(MainActivity.kt:13)
                                                                              at android.app.Activity.performCreate(Activity.java:6285)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524) 
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:154) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:234) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5526) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                           Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.bowyer.app.fabtransitionlayout.BottomSheetLayout
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                              at twogetherbank.com.lottie.MainActivity.onCreate(MainActivity.kt:13) 
                                                                              at android.app.Activity.performCreate(Activity.java:6285) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524) 
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:154) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:234) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5526) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                           Caused by: java.lang.reflect.InvocationTargetException
                                                                              at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                              at twogetherbank.com.lottie.MainActivity.onCreate(MainActivity.kt:13) 
                                                                              at android.app.Activity.performCreate(Activity.java:6285) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524) 
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:154) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:234) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5526) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                           Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class io.codetail.widget.RevealLinearLayout
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                              at android.view.View.inflate(View.java:19876)
                                                                              at com.bowyer.app.fabtransitionlayout.BottomSheetLayout.init(BottomSheetLayout.java:85)
                                                                              at com.bowyer.app.fabtransitionlayout.BottomSheetLayout.<init>(BottomSheetLayout.java:74)
                                                                              at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                              at twogetherbank.com.lottie.MainActivity.onCreate(MainActivity.kt:13) 
                                                                              at android.app.Activity.performCreate(Activity.java:6285) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524) 
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:154) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:234) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5526) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                           Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class io.codetail.widget.RevealLinearLayout
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                              at android.view.View.inflate(View.java:19876) 
                                                                              at com.bowyer.app.fabtransitionlayout.BottomSheetLayout.init(BottomSheetLayout.java:85) 
                                                                              at com.bowyer.app.fabtransitionlayout.BottomSheetLayout.<init>(BottomSheetLayout.java:74) 
                                                                              at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                              at twogetherbank.com.lottie.MainActivity.onCreate(MainActivity.kt:13) 
                                                                              at android.app.Activity.performCreate(Activity.java:6285) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524) 
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:154) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:234) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5526) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "io.codetail.widget.RevealLinearLayout" on path: DexPathList[[zip file "/data/app/twogetherbank.com.lottie-1/base.apk", zip file "/d

I don't know how to solve it. I think that the problem is the old version of CircularReveal.

**Comment by camrongiuliani** [comment]
Same issue here. Were you able to come up with a resolution? Appears to happen when importing the library as a module. Simply using the gradle dependency it works.

**Comment by gabrielkdc** [comment]
I added 

  implementation ('com.github.ozodrukh:CircularReveal:2.0.1@aar') {
        transitive = true;
    }

To my dependencies and it is working now
